# 数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_blog?serverTimezone=UTC
    username: root
    password: 123456

    initial-size: 5
    min-idle: 5
    max-active: 20
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 30000
    filters: sta
    async-init: true
    #thymeleaf缓存关闭
  thymeleaf:
    cache: false
#    redis配置
  redis:
    host: 192.168.226.138
    port: 6379

  #mybatis别名配置
mybatis-plus:
  type-aliases-package: net.togogo.blog.entity
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    net.togogo.blog: debug